### ISSUE TITLE
Latest helm image is using helm@3 which broke existing Github CI

### ISSUE THREAD

**Issue by nirav24** [igabaydulin/helm-check-action#3]
**Describe the bug**
I have been using this GitHub action to validate my helm chart. It was working fine until today when `alpine/helm` is using `helm@3.1.2`.

I think, it is good practice to freeze version.

For my usecase, I have done https://github.com/nirav24/helm-check-action/commit/1de08320c4586b401c494c9c826dd11fc74f0810.

I am happy to submit PR if you are okay with it. I just don't know where I should submit it.

**Comment by igabaydulin** [comment]
@nirav24 Yes, it's definitely a good idea, we have fixed it, sorry it took too much time, I should manage my notifications better :disappointed:

To submit changes you can create PR from your fork. Here is a [link](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) to GitHub article describing how to do it.

I'm closing this issue now, if there's still a problem with it, let me know

**Comment by nirav24** [comment]
@igabaydulin no problem. Thanks for fixing it. I think, my changes are covered in `v0.1.5`.
